// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiosWeb.API.Data;

public partial class ComputerHardware
{
    public int Id { get; set; }

    public int? TypeId { get; set; }

    public string Brand { get; set; }

    public string Model { get; set; }

    public decimal Price { get; set; }

    public virtual ICollection<HardwareSpec> HardwareSpecs { get; set; } = new List<HardwareSpec>();

    public virtual ICollection<OfferItem> OfferItems { get; set; } = new List<OfferItem>();

    public virtual HardwareType Type { get; set; }
}