// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiosWeb.API.Data;

public partial class HardwareSpec
{
    public int Id { get; set; }

    public int? HardwareId { get; set; }

    public string SpecKey { get; set; }

    public string SpecValue { get; set; }

    public virtual ComputerHardware Hardware { get; set; }
}