// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiosWeb.API.Data;

public partial class HardwareType
{
    public int Id { get; set; }

    public string TypeName { get; set; }

    public virtual ICollection<ComputerHardware> ComputerHardwares { get; set; } = new List<ComputerHardware>();
}