// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiosWeb.API.Data;

public partial class Offer
{
    public int Id { get; set; }

    public DateTime DateCreated { get; set; }

    public DateTime DateChanged { get; set; }

    public virtual ICollection<OfferItem> OfferItems { get; set; } = new List<OfferItem>();
}